### ISSUE TITLE
Лабы по ООП

### ISSUE THREAD

**Issue by demidov91** [Drapegnik/bsuir#1]
Есть вот такая штука: лабы по ооп на python(3.7), tkinter. У вас всё равно ПЗ на 3 дня позже чем у нас, так что не жалко.

https://github.com/demidov91/university-oop-geometry/

**Comment by Drapegnik** [comment]
@demidov91, а дакладна можна на пітоне здаваць? а то я рабіў ужо нешта [падобнае](https://github.com/Drapegnik/bsu/tree/master/technology/lab1), але падумаў што не падыйдзе

**Comment by demidov91** [comment]
Так, падыходзіў да Краскоўскага - гаворыць, усё можна: java, c#, python, go. Толькі ў js не верыць, але калі ўсё будзе выканана як напісана, то і js задаволіць.

**Comment by demidov91** [comment]
Гаворыць, крытычна - каб можна было дадаваць новыя плагіны як dll. Пытаю: "У выпадку пітона гаворка ідзе пра модулі?" - "Так"

**Comment by Drapegnik** [comment]
@demidov91, дзякуй, у выніку зрабіў сам - https://github.com/Drapegnik/oop-paint
